# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ehrMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Mixpanel'
  pod 'react-native-mixpanel', :path => '../node_modules/react-native-mixpanel'

  # this is very important to have!
  rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]



  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNIap', :path => '../node_modules/react-native-iap'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

end



# very important to have, unless you removed React dependencies for Libraries 
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end

    if target.name == "yoga"
      target.remove_from_project
    end
  end
end

